<?php

declare(strict_types=1);

namespace Pollora\Doctor\Infrastructure\Checks;

use Pollora\Doctor\Domain\Contracts\CheckInterface;
use Pollora\Doctor\Domain\Enums\RunContext;
use Pollora\Doctor\Domain\Models\CheckResult;
use Pollora\Doctor\Infrastructure\Support\ProjectModule;
use Pollora\Doctor\Infrastructure\Support\ProjectModules;

/**
 * No theme or plugin still carries its template's placeholders.
 *
 * Theme and plugin templates (theme-default, theme-buzz, plugin-default…) are
 * meant to be generated by pollora:make:theme and pollora:make:plugin, which
 * substitute %theme_*% / %plugin_*% and turn the .stub files into PHP. A copy
 * keeps them, and the first sign is a syntax error on `namespace %theme_namespace%`.
 */
final readonly class TemplatePlaceholdersCheck implements CheckInterface
{
    private const array PATTERNS = [
        'theme' => '/%theme_[a-z_]+%/i',
        'plugin' => '/%plugin_[a-z_]+%/i',
    ];

    private const array COMMANDS = [
        'theme' => 'php artisan pollora:make:theme %s --repository=<owner/template-repository>',
        'plugin' => 'php artisan pollora:make:plugin %s',
    ];

    public function __construct(private ProjectModules $modules) {}

    public function id(): string
    {
        return 'template-placeholders';
    }

    public function label(): string
    {
        return 'Template placeholders';
    }

    public function runsIn(): array
    {
        return [RunContext::Console, RunContext::Http];
    }

    public function run(RunContext $context): CheckResult
    {
        $problems = [];
        $fixes = [];

        foreach ($this->modules->all() as $module) {
            if (! isset(self::PATTERNS[$module->type])) {
                continue;
            }

            $files = $this->filesWithPlaceholders($module);

            if ($files === []) {
                continue;
            }

            $problems[] = sprintf('%s: %s', $module->label(), implode(', ', array_slice($files, 0, 5)).(count($files) > 5 ? sprintf(' (+%d)', count($files) - 5) : ''));
            $fixes[] = sprintf(self::COMMANDS[$module->type], $module->name);
        }

        if ($problems !== []) {
            return CheckResult::error(
                sprintf('%d module(s) were copied from a template instead of generated: they still carry its placeholders.', count($problems)),
                $problems,
                implode(' ; ', $fixes),
            );
        }

        return CheckResult::ok('No template placeholder left.');
    }

    /**
     * @return list<string>
     */
    private function filesWithPlaceholders(ProjectModule $module): array
    {
        $pattern = self::PATTERNS[$module->type];
        $files = [];

        foreach ($module->files('', ['php', 'css', 'js', 'jsx', 'ts', 'tsx', 'json', 'html', 'stub']) as $file) {
            if (str_ends_with($file, '.stub') || preg_match($pattern, $file) === 1 || preg_match($pattern, (string) file_get_contents($module->root.'/'.$file)) === 1) {
                $files[] = $file;
            }
        }

        return $files;
    }
}
