<?php

declare(strict_types=1);

namespace Pollora\Doctor\Infrastructure\Checks;

use Pollora\Doctor\Domain\Contracts\CheckInterface;
use Pollora\Doctor\Domain\Enums\RunContext;
use Pollora\Doctor\Domain\Models\CheckResult;
use Pollora\Doctor\Infrastructure\Support\ActiveTheme;

/**
 * The active theme carries no %theme_*% placeholder.
 *
 * Theme templates (theme-default, theme-apiary, theme-buzz) are meant to be
 * generated by pollora:make:theme, which substitutes them. A clone keeps them,
 * and the first sign is a PHP syntax error on `namespace %theme_namespace%`.
 */
final readonly class ThemePlaceholdersCheck implements CheckInterface
{
    public function id(): string
    {
        return 'theme-placeholders';
    }

    public function label(): string
    {
        return 'Theme placeholders';
    }

    public function runsIn(): array
    {
        return [RunContext::Console, RunContext::Http];
    }

    public function run(RunContext $context): CheckResult
    {
        $directory = ActiveTheme::directory();

        if ($directory === null || ! is_dir($directory)) {
            return CheckResult::skipped('No active theme directory.');
        }

        $carrying = array_values(array_filter(
            ActiveTheme::files('', ['php', 'css', 'js', 'jsx', 'ts', 'tsx', 'json', 'html']),
            static fn (string $file): bool => preg_match('/%theme_[a-z_]+%/', (string) file_get_contents($directory.'/'.$file)) === 1,
        ));

        if ($carrying !== []) {
            return CheckResult::error(
                sprintf('%d file(s) still carry %%theme_*%% placeholders: the theme was copied from a template instead of generated.', count($carrying)),
                array_slice($carrying, 0, 20),
                sprintf('php artisan pollora:make:theme %s --repository=<owner/template-repository>', ActiveTheme::slug() ?? 'my-theme'),
            );
        }

        return CheckResult::ok('No placeholder left in the theme.');
    }
}
